<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Projet web DD : Add</title>
        
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="style_menu.css">


    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
       
    </head>
    
	
	<body>
        <div>
    <nav class="navbar navbar-dark bg-dark">

        <a class="navbar-brand" href="/menu">Mangachier</a>
         <p></p>
        <p></p>
        <a class="navbar-brand" href="/add">Add</a>

</nav>
</div>
 <p></p> <p></p>

 <h1>
Création d'une nouvelle ligne du tableau
 </h1> 
 <p></p> <p></p>

	<form method="post" action="/added" class = "form_add">
        <div class="form-group">
    <p><label>Titre</label> : <input type="text" name="title" /></p>
    <p><label>Nb d'éps</label> : <input type="number" name="episodesnb" min=1 step=1 /></p>

    <p>	
 <label>Genre</label>     
<select name="genre">

           <option value="action">Action</option>
           <option value="aventure">Aventure</option>
           <option value="horreur">Horreur</option>
           <option value="romance">Romance</option>
           <option value="mystère">Mystère</option>
           <option value="scifi">Sci-Fi</option>

       </select>
</p>

 <p><label>Description</label> : <input type="text" name="description" /></p>
</div>
<input type="submit" value="Créer" />
</form>

             <p><a href="/menu">Revenir au menu principal </a></p>
    </body>
</html>
