<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Projet web DD : Added</title>
          
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="style_menu.css">


    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
    </head>
    <body>
     <nav class="navbar navbar-dark bg-dark">

        <a class="navbar-brand" href="/menu">Mangachier</a>
        <a class="navbar-brand" href="/add">Add</a>

</nav>
</div>
<p></p><p></p><p></p>
<h1> Cette ligne a bien été ajoutée ! </h1>
<p></p><p></p><p></p>
            <p><a href="/menu">Revenir au menu principal </a></p>
		
    </body>
</html>