<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Projet web DD</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="style_menu.css">


    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
</head>



<body>
  <!--  <h1> Mangachier </h1>
    <div class = "intro">Base de données : Mangas</div>-->
    <nav class="navbar navbar-dark bg-dark">

        <a class="navbar-brand" href="/menu">Mangachier</a>
        <p></p>
        <p></p>
        <a class="navbar-brand" href="/show">Show</a>
        <a class="navbar-brand" href="/add">Add</a>
        <a class="navbar-brand" href="/update">Update</a>
        <a class="navbar-brand" href="/delete">Delete</a>
        <form class="form-inline">
          <input name="search" type="text" placeholder="search"/>
          <input type="submit">
        </form>
</nav>


<div>
    <table class="table table-bordered table-striped">
        <tr>
            <th> id </th>
            <th> Titre du manga </th>
            <th> Nombre d'épisodes </th>
            <th> Genre </th>
            <th> Description </th>
            <th></th>
        </tr>
        <?php foreach ($mangas as $manga) :?>
        <tr>


         <td><?=$manga->id?></td>

         <td><?=$manga->title?></td>

         <td><?=$manga->episodesnb?></td>

         <td><?=$manga->genre?></td>

         <td><?=$manga->description?></td>


         <td>
           <div class="row">
            <form method="post" class="form-inline" action="/update">
              <input type="hidden" name="id" value="<?=$manga->id?>"/>
             <input type="submit" class="btn btn-primary" value="Editer"/>
           </form>
           <form class="form-inline" method="post" action="/deleted">
            <input type="hidden" name="id" value="<?=$manga->id?>"/>
             <input type="submit" class="btn btn-primary" value="Supprimer"/>
           </form>
         </div>
        </td>

     </tr>
 <?php endforeach; ?>
</table>
</div>

</body>
</html>
