<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Projet web DD : Add</title>
        
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="style_menu.css">


    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
       
    </head>
    
  
  <body>
        <div>
    <nav class="navbar navbar-dark bg-dark">

        <a class="navbar-brand" href="/menu">Mangachier</a>
         <p></p>
        <p></p>
        <a class="navbar-brand" href="/show">Show</a>
        <a class="navbar-brand" href="/add">Add</a>
        <a class="navbar-brand" href="/update">Update</a>
        <a class="navbar-brand" href="/delete">Delete</a>

</nav>
</div>


             <p><a href="/menu">Revenir au menu principal </a></p>
    </body>
</html>
