<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Projet web DD : Show</title>
          
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="style_menu.css">


    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
    </head>
    <body>
 

        <h1>Showing the database</h1>
      
<div>		
			<table>
			<tr>
                <th> id </th>
				<th> Titre du manga </th>
				<th> Nombre d'épisodes </th>
				<th> Genre </th>
			</tr>
<?php foreach ($mangas as $manga) :?> 
   <tr>


       <td><?=$manga->id?></td>

       <td><?=$manga->title?></td>

       <td><?=$manga->episodesnb?></td>

       <td><?=$manga->genre?></td>

          <td><?=$manga->description?></td>

   </tr>
   <?php endforeach; ?>
</table>
</div>	
		<p><a href="/menu"> Revenir au menu principal </a></p>	
        
    </body>
</html>