<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Projet web DD : Update</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>

    </head>
    <body>
        <h1>Showing the database</h1>

<form method="post" action="/updated">
    <p><label>id</label> : <input type="number" name="id" min=1 step=1 value="<?=$mangas->id?>"/></p>

    <p><label>Titre</label> : <input type="text" name="title" value="<?=$mangas->title?>" /></p>
    <p><label>Nombre d'épisodes</label> : <input type="number" name="episodesnb" value="<?=$mangas->episodesnb?>" min=1 step=1 /></p>

    <p>
 <label>Genre</label>
<select name="genre">

           <option value="action" >Action</option>
           <option value="aventure">Aventure</option>
           <option value="horreur">Horreur</option>
           <option value="romance">Romance</option>
           <option value="mystère">Mystère</option>
           <option value="scifi">Sci-Fi</option>
           <option value="<?=$mangas->genre?>" selected><?=$mangas->genre;?></option>

       </select>
</p>
<p>
  <label>Description</label>
  <input name="description" type="area" value="<?=$mangas->description?>"/>
</p>
<input type="submit" value="Mettre à jour" />
</form>


		<p><a href="/menu"> Revenir au menu principal </a></p>

    </body>
</html>
