<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Projet web DD : Update</title>
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="style_menu.css">


    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
    </head>
    <body>
               <div>
    <nav class="navbar navbar-dark bg-dark">

        <a class="navbar-brand" href="/menu">Mangachier</a>
        <a class="navbar-brand" href="/add">Add</a>

</nav>
</div>

 <p></p> <p></p>

 <h1> Mise à jour d'une ligne </h1>

 <p></p>

<form method="post" action="/updated" class = "form_add">
   <div class="form-group">
    <p><label>id</label> : <input type="number" name="id" min=1 step=1 value="<?=$mangas->id?>"/></p>

    <p><label>Titre</label> : <input type="text" name="title" value="<?=$mangas->title?>" /></p>
    <p><label>Nombre d'épisodes</label> : <input type="number" name="episodesnb" value="<?=$mangas->episodesnb?>" min=1 step=1 /></p>

    <p>
 <label>Genre</label>
<select name="genre">

           <option value="action" >Action</option>
           <option value="aventure">Aventure</option>
           <option value="horreur">Horreur</option>
           <option value="romance">Romance</option>
           <option value="mystère">Mystère</option>
           <option value="scifi">Sci-Fi</option>
           <option value="<?=$mangas->genre?>" selected><?=$mangas->genre;?></option>

       </select>
</p>
<p>
  <label>Description</label>
</div>
  <input name="description" type="area" value="<?=$mangas->description?>"/>
</p>
<input type="submit" value="Mettre à jour" />
</form>


		<p><a href="/menu"> Revenir au menu principal </a></p>

    </body>
</html>
